### ISSUE TITLE
unexpected result from npm init

### ISSUE THREAD

**Issue by zibbizor** [crazy-max/neard#108]
Neard's Node.js package is unable to produce a proper output with the npm init command. This command should ask you some information related to your package, whereas with neard it does not ask you anything and will generate an empty package.json.

```
npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg> --save` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
About to write to D:\neard\www\testnode\package.json:

{
  "name": "",
  "version": ""
}


Is this ok? (yes)
```

I have attempted the same with a regular Node.js install from the official website and it works as expected.

**Comment by crazy-max** [comment]
Thanks for your feedback!
Can you send your package.json ?

**Comment by crazy-max** [comment]
My bad, you want the init npm tutorial ?

**Comment by crazy-max** [comment]
What release do you download from the official website ?

**Comment by crazy-max** [comment]
And can you paste the output of the command ``npm init --verbose`` ?

**Comment by crazy-max** [comment]
Ok the problem comes from the npmrc global file.

For a quick fix, you can edit the file ``npmrc`` in ``C:\neard\bin\nodejs\nodejs0.12.4\node_modules\npm``

Replace ``init-module = X:\dev\neard\bin\nodejs\nodejs0.12.4\node_modules\npm\init.js``
With ``init-module = X:\dev\neard\bin\nodejs\nodejs0.12.4\node_modules\npm\.npm-init.js``

Will be fixed in the next release of [neard-bin-nodejs](https://github.com/crazy-max/neard-bin-nodejs)

**Comment by crazy-max** [comment]
Solved on [neard-bin-nodejs r2](https://github.com/crazy-max/neard-bin-nodejs)
