### ISSUE TITLE
Always need a restart to run Neard

### ISSUE THREAD

**Issue by in-code** [crazy-max/neard#118]
Hi,
every time I first start Neard a message appear who ask me to restart to apply new parameters. Then it work fine but I have to wait twice to start the app.

In French: 
![nearparametersrestart](https://cloud.githubusercontent.com/assets/12280987/14493204/7d86f5d4-0184-11e6-879a-d8650d43106a.png)
> Neard 1.0.17 - Redémarrer
> (!) Veuillez redémarer Neard pour appliquer les nouveaux paramètres ...

Can you help me to fix this?

**Comment by btoplak** [comment]
The same happens to me! It's a bit annoying so it would be great if there was some workaround.

Btw. congrats on great piece of software!

**Comment by crazy-max** [comment]
Hi,

Please read "Found a bug?" section in the README.md and give me the informations.

Thanks

**Comment by iansebryk** [comment]
having same problem.  will upload results at next rebooot, because the issue only seems to appear after a reboot.  system is running Win10 Pro with Neard v1.0.17.  other than this somewhat irritating issue, Neard runs flawlessly :100:.  were it not for the long startup time, this would likely be unimportant.  :)

**Comment by crazy-max** [comment]
@iansebryk After inspecting your logs it seems to come from a reboot of your computer without stop Neard before. Then the service is "marked for delete" (430) so Neard cannot use the service and needs to restart. I will implement a new way to check if the service is already installed and use it if the bin path and arguments are the same.

For the moment the solution is to exit Neard before restarting or turn off your computer.

Neard is portable so each start must inspect and correct paths (scan folders) and it's a long process depends of the number of bins added. Eache start install services and each stop remove services and this process is quite long too. That's why the startup time can be long.

**Comment by iansebryk** [comment]
Max: thanks for getting back to me.  for those not privy, Neard requires a restart if you reboot your machine before shutting Neard down.  so if you kill Neard, then reboot, no problem.  this will be looked at in a future release.  so until then: shutdown Neard then machine.  :+1:

**Comment by iansebryk** [comment]
thank you so much.  good to know what's clicking there.  thank you for all you hard work. :+1:

**Comment by crazy-max** [comment]
@iansebryk You're welcome and thanks for your support ;)
Btw do you use Filezilla on Neard ? Because the problem seems to be on this binary.

**Comment by crazy-max** [comment]
Solved on Neard 1.0.18
