### ISSUE TITLE
Apache mod_filter

### ISSUE THREAD

**Issue by StaggerLeee** [crazy-max/neard#234]
Can you please make it activated by default on Apache 2.4 and above versions ?
Seems as for some reason WordPress WP-SpamShield needs it to work, and install right.

https://wordpress.org/plugins/wp-spamshield/

**Comment by crazy-max** [comment]
Hi,

Since it's specific to an application (here Wordpress) i cannot make it as a default enabled module.
You have to do this on your own by going to **Neard tray icon > Apache > Modules > filter_module**

![image](https://cloud.githubusercontent.com/assets/1951866/24083247/ed2bd69c-0cd3-11e7-8519-12b99deb32e5.png)

If i have to enable an Apache module for all the existing applications on Internet by default in the Apache bundles i will have to make a release every hour 😉 

Thanks for your understanding

**Comment by StaggerLeee** [comment]
Hi Max

It is OK and understandable. You would just make your Wamp slow and reject new Users. 

Let this issue be here if some other people have problems with it. I know now it is something in Apache 2.4. That is why I did not have problems with this plugin in Apache 2.2 version.

**Comment by crazy-max** [comment]
Yes i keep this issue in my backlog
